AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  repoWebhook:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: repoWebhook/index.handler
      Runtime: nodejs8.10
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role:
        'Fn::Sub': 'arn:aws:iam::${AWS::AccountId}:role/lambda_basic_execute_role'
      Events:
        LambdaMicroservice:
          Type: Api
          Properties:
            Path: /repo
            Method: POST
      Environment:
        Variables:
          SECRET_NAME: specialist/poc/cicd
  repoWebhookPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        'Fn::GetAtt':
          - repoWebhook
          - Arn
      Principal: apigateway.amazonaws.com
  createCodeBuild:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: createCodeBuild/index.handler
      Runtime: nodejs8.10
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role:
        'Fn::Sub': 'arn:aws:iam::${AWS::AccountId}:role/lambda_basic_execute_role'
  createWebHook:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: createWebHook/lambda_function.lambda_handler
      Runtime: python3.6
      Description: ''
      MemorySize: 128
      Timeout: 15
      Role:
        'Fn::Sub': 'arn:aws:iam::${AWS::AccountId}:role/lambda_basic_execute_role'
      CodeUri: .debug/
      Environment:
        Variables:
          SECRET_NAME: specialist/poc/cicd